"""create and updating user model field's and create the pydantic file for validation data

Revision ID: 15f4520977f2
Revises: 840d9e1ce413
Create Date: 2026-09-01 00:09:53.926429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '15f4520977f2'
down_revision: Union[str, Sequence[str], None] = '840d9e1ce413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    user_status = postgresql.ENUM(
        'active', 'inactive', 'suspended', 'pending', 'blocked',
        name='enuserstatus', create_type=False
    )
    user_role = postgresql.ENUM(
        'admin', 'user', 'guest', 'super_admin',
        name='enuserrole', create_type=False
    )
    permission_level = postgresql.ENUM(
        'read', 'write', 'delete', 'full',
        name='enpermissionlevel', create_type=False
    )
    gender = postgresql.ENUM(
        'male', 'female', 'other', 'prefer_not_to_say',
        name='engender', create_type=False
    )

    bind = op.get_bind()
    for enum_type in (user_status, user_role, permission_level, gender):
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblUsers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', user_status, server_default='pending', nullable=False),
    sa.Column('role', user_role, server_default='user', nullable=False),
    sa.Column('permission_level', permission_level, server_default='read', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_tblUsers_id'), 'tblUsers', ['id'], unique=False)
    op.create_index(op.f('ix_tblUsers_is_delete'), 'tblUsers', ['is_delete'], unique=False)
    op.create_index(op.f('ix_tblUsers_username'), 'tblUsers', ['username'], unique=True)
    op.create_table('tblProfile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bio', sa.Text, nullable=True),
    sa.Column('profile_url', sa.String(length=250), nullable=True),
    sa.Column('national_id', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gender', gender, nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text, nullable=True),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_fk'], ['tblUsers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('user_id_fk')
    )
    op.create_index(op.f('ix_tblProfile_id'), 'tblProfile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tblProfile_id'), table_name='tblProfile')
    op.drop_table('tblProfile')
    op.drop_index(op.f('ix_tblUsers_username'), table_name='tblUsers')
    op.drop_index(op.f('ix_tblUsers_is_delete'), table_name='tblUsers')
    op.drop_index(op.f('ix_tblUsers_id'), table_name='tblUsers')
    op.drop_table('tblUsers')
    bind = op.get_bind()
    for enum_name in ('engender', 'enpermissionlevel', 'enuserrole', 'enuserstatus'):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
