"""connected the Task and User model's

Revision ID: 36ed7a59a82a
Revises: 15f4520977f2
Create Date: 2026-09-03 09:59:47.013714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ed7a59a82a'
down_revision: Union[str, Sequence[str], None] = '15f4520977f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tblUsers', ['user_id_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id_fk')
    # ### end Alembic commands ###
